apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    nodePort: 21
    name: ftps
  - port: 21000
    targetPort: 21000
    nodePort: 21000
    name: ftps-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 21000
          name: ftps-data
